export const EQ1 = [
  { id:1, match:"vs Clermont Métropole", date:"Sept 2024", sortKey:1, entries:[
    {player:"Yanis",amount:8,detail:"Bienvenue + 10 buts pris + meilleure action"},
    {player:"Fred",amount:10,detail:"Bienvenue + 10 buts pris + 2 relances ratées"},
    {player:"Adrien",amount:8,detail:"Bienvenue + meilleur buteur + tir fantaisie raté + contre-attaque ratée"},
    {player:"Gabin",amount:5,detail:"Bienvenue + penalty raté"},
    {player:"Thomas",amount:3,detail:"Bienvenue"},
    {player:"Paul",amount:8,detail:"Bienvenue + poule non off."},
    {player:"Rémi",amount:3,detail:"Bienvenue"},
    {player:"Simon",amount:3,detail:"Bienvenue"},
    {player:"Théo",amount:6,detail:"Bienvenue + mitraillette"},
    {player:"Alexis",amount:10,detail:"Bienvenue + chaboulat + contre-attaque ratée"},
    {player:"Meyro",amount:3,detail:"Bienvenue"},
    {player:"Lenny",amount:5,detail:"Bienvenue + contre-attaque ratée"},
  ]},
  { id:2, match:"vs Pérignat", date:"Oct 2024", sortKey:2, entries:[
    {player:"Yanis",amount:4,detail:"Relance ratée + tirs fantaisie pris"},
    {player:"Fred",amount:6,detail:"Meilleure action + 2 relances ratées"},
    {player:"Adrien",amount:14,detail:"Chaboulat + non port chaboulat photo + tir fantaisie raté + contre-attaque ratée + pastis"},
    {player:"Gabin",amount:8,detail:"Meilleur buteur + meilleure action + poule non off."},
    {player:"Thomas",amount:3,detail:"Mitraillette"},
    {player:"Paul",amount:11,detail:"Serviette entraînement + gourde entraînement + mitraillette + 2 tirs fantaisie ratés"},
    {player:"Hugo",amount:6,detail:"Bienvenue + mitraillette"},
    {player:"Simon",amount:3,detail:"Fantôme"},
    {player:"Théo",amount:7,detail:"Retard 2 min + contre-attaque ratée + 2 min contestation"},
    {player:"Alexis",amount:2,detail:"Photo oublié chaboulat"},
    {player:"Meyro",amount:4,detail:"Fantôme + oubli caleçon"},
    {player:"Lenny",amount:0,detail:"Rien"},
  ]},
  { id:3, match:"vs Le Puy", date:"Oct 2024", sortKey:3, entries:[
    {player:"Yanis",amount:6,detail:"2 relances ratées + meilleure action"},
    {player:"Fred",amount:4,detail:"2 relances ratées"},
    {player:"Adrien",amount:0,detail:"Rien"},
    {player:"Gabin",amount:6,detail:"2 contre-attaques ratées + tir fantaisie raté"},
    {player:"Thomas",amount:5,detail:"5 min retard entraînement"},
    {player:"Paul",amount:3,detail:"Chasuble + gel douche"},
    {player:"Hugo",amount:7,detail:"Chaboula + short entraînement"},
    {player:"Simon",amount:9,detail:"Mitraillette + tir fantaisie + 2 contre-attaques ratées"},
    {player:"Théo",amount:11,detail:"Retard 4 min + contre-attaque ratée + chasuble + mitraillette"},
    {player:"Alexis",amount:6,detail:"Retard 3 min + mitraillette"},
    {player:"David",amount:3,detail:"Fantôme"},
    {player:"Lenny",amount:0,detail:"Rien"},
  ]},
  { id:4, match:"vs Yssingeaux", date:"Oct 2024", sortKey:4, entries:[
    {player:"Yanis",amount:0,detail:"Rien"},
    {player:"Fred",amount:14,detail:"Sortie veille + chaboulat + 2 relances"},
    {player:"Adrien",amount:2,detail:"Penalty raté"},
    {player:"Gabin",amount:4,detail:"Penalty + tir fantaisie raté"},
    {player:"Thomas",amount:7,detail:"Mitraillette + 2 tirs pivots ratés"},
    {player:"Paul",amount:6,detail:"Poule non off. + meilleur buteur"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Simon",amount:2,detail:"Meilleure action"},
    {player:"Théo",amount:3,detail:"Mitraillette"},
    {player:"Alexis",amount:8,detail:"Contre-attaque ratée + puit de pétrole + mitraillette"},
    {player:"Meyro",amount:0,detail:"Rien"},
    {player:"Lenny",amount:5,detail:"Vomi en soirée"},
  ]},
  { id:5, match:"vs St Germain", date:"Nov 2024", sortKey:5, entries:[
    {player:"Yanis",amount:8,detail:"Sortie veille + mitraillette"},
    {player:"Fred",amount:6,detail:"Sortie veille + tir fantaisie pris"},
    {player:"Adrien",amount:3,detail:"Mitraillette"},
    {player:"Gabin",amount:8,detail:"Sortie veille + penalty raté + meilleur buteur"},
    {player:"Thomas",amount:7,detail:"Chaboulat + contre-attaque ratée"},
    {player:"Paul",amount:13,detail:"Sortie veille + mitraillette + tir fantaisie + 2 min contestation"},
    {player:"Hugo",amount:4,detail:"Tir fantaisie raté + 2 tirs pivot ratés"},
    {player:"Simon",amount:0,detail:"Rien"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Alexis",amount:5,detail:"Sortie veille"},
    {player:"Lenny",amount:0,detail:"Rien"},
  ]},
  { id:6, match:"vs St Flour (Coupe de France)", date:"Nov 2024", sortKey:6, entries:[
    {player:"Yanis",amount:31,detail:"Sortie veille + 7 tirs fantaisie pris + 2 relances ratées + 10 buts pris"},
    {player:"Adrien",amount:6,detail:"Meilleur buteur"},
    {player:"Gabin",amount:15,detail:"Sortie veille + téléphone banc + mitraillette"},
    {player:"Thomas",amount:10,detail:"Sortie veille"},
    {player:"Paul",amount:21,detail:"Sortie veille + mitraillette + 2 min contestation + pno"},
    {player:"Simon",amount:13,detail:"Chaboulat + mitraillette"},
    {player:"Théo",amount:16,detail:"Sortie veille + mitraillette + retard 3 min"},
    {player:"Alexis",amount:13,detail:"Sortie veille + mitraillette"},
    {player:"Lenny",amount:17,detail:"Sortie veille + 2 contre-attaques ratées + mitraillette"},
    {player:"David",amount:11,detail:"Mitraillette + puit de pétrole"},
    {player:"Mathieu",amount:13,detail:"Sortie veille + mitraillette"},
    {player:"Rémi",amount:13,detail:"Sortie veille + mitraillette"},
  ]},
  { id:7, match:"vs Romagnat", date:"Nov 2024", sortKey:7, entries:[
    {player:"Yanis",amount:11,detail:"Sortie veille + 10 buts pris par un joueur"},
    {player:"Fred",amount:8,detail:"Relance ratée + 10 buts pris par un joueur"},
    {player:"Adrien",amount:5,detail:"Tir fantaisie raté + défaite 7/9 buts"},
    {player:"Gabin",amount:10,detail:"Sortie veille + penalty raté"},
    {player:"Thomas",amount:3,detail:"Défaite 7/9 buts"},
    {player:"Paul",amount:16,detail:"Sortie veille + chaboulat + 2 min contestation"},
    {player:"Simon",amount:2,detail:"Non port chaboulat"},
    {player:"Théo",amount:16,detail:"Sortie veille + mitraillette + retard 5 min"},
    {player:"Arthur",amount:6,detail:"Mitraillette"},
    {player:"Lenny",amount:3,detail:"Défaite"},
    {player:"Kevin",amount:6,detail:"Mitraillette"},
    {player:"Hugo",amount:3,detail:"Défaite"},
  ]},
  { id:8, match:"vs Yssingeaux (2)", date:"Déc 2024", sortKey:8, entries:[
    {player:"Fred",amount:0,detail:"Rien"},
    {player:"Adrien",amount:3,detail:"Mitraillette"},
    {player:"Gabin",amount:4,detail:"Mitraillette + meilleur buteur"},
    {player:"Paul",amount:20,detail:"Carton rouge"},
    {player:"Simon",amount:0,detail:"Rien"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Arthur",amount:6,detail:"Mitraillette + chaboula"},
    {player:"Lenny",amount:1,detail:"Meilleur buteur"},
    {player:"Kevin",amount:3,detail:"Meilleur buteur + meilleure action"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Alexis",amount:3,detail:"Mitraillette"},
    {player:"Rémi",amount:0,detail:"Rien"},
    {player:"Meyro",amount:1,detail:"Meilleur buteur"},
  ]},
  { id:9, match:"vs Est 43", date:"Déc 2024", sortKey:9, entries:[
    {player:"Fred",amount:6,detail:"Sortie veille"},
    {player:"Adrien",amount:8,detail:"Chaboula + penalty bien raté"},
    {player:"Gabin",amount:10,detail:"Retard 3 min + 2 penalty ratés + meilleur buteur"},
    {player:"Paul",amount:1,detail:"Movember"},
    {player:"Simon",amount:4,detail:"Mitraillette"},
    {player:"Théo",amount:15,detail:"Non respect Movember + retard 5 min + sortie veille"},
    {player:"Lenny",amount:11,detail:"Non respect Movember + vomi soirée + meilleur buteur"},
    {player:"Kevin",amount:5,detail:"Movember"},
    {player:"Hugo",amount:1,detail:"Movember"},
    {player:"Benjamin",amount:1,detail:"Movember"},
    {player:"Meyro",amount:1,detail:"Movember"},
    {player:"Yanis",amount:10,detail:"Sortie veille + 2 relances ratées"},
  ]},
  { id:10, match:"vs Chamalière", date:"Déc 2024", sortKey:10, entries:[
    {player:"Fred",amount:5,detail:"Sortie veille"},
    {player:"Adrien",amount:0,detail:"Rien"},
    {player:"Gabin",amount:3,detail:"Chaboula"},
    {player:"Paul",amount:15,detail:"3x2 min + mitraillette + short oublié"},
    {player:"Théo",amount:5,detail:"Sortie veille"},
    {player:"Lenny",amount:0,detail:"Rien"},
    {player:"Kevin",amount:0,detail:"Rien"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Alexis",amount:0,detail:"Rien"},
    {player:"Thomas",amount:0,detail:"Rien"},
    {player:"Meyro",amount:0,detail:"Rien"},
    {player:"Yanis",amount:10,detail:"Sortie veille + 2 tirs fantaisie"},
  ]},
  { id:11, match:"vs Aurillac", date:"Jan 2025", sortKey:11, entries:[
    {player:"Fred",amount:5,detail:"10 buts pris + relance ratée"},
    {player:"Adrien",amount:2,detail:"Penalty raté"},
    {player:"Gabin",amount:9,detail:"Meilleur buteur + meilleure action + 2 contre-attaques + tir fantaisie raté"},
    {player:"Paul",amount:1,detail:"Meilleure action"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Lenny",amount:0,detail:"Rien"},
    {player:"Kevin",amount:7,detail:"Chaboulat + contre-attaque"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Simon",amount:3,detail:"Mitraillette"},
    {player:"Thomas",amount:0,detail:"Rien"},
    {player:"Meyro",amount:3,detail:"Mitraillette"},
    {player:"Yanis",amount:3,detail:"10 buts pris par le même joueur"},
  ]},
  { id:12, match:"vs Vichy", date:"Jan 2025", sortKey:12, entries:[
    {player:"Fred",amount:2,detail:"Meilleure action"},
    {player:"Adrien",amount:2,detail:"Penalty raté"},
    {player:"Paul",amount:13,detail:"Chaboulat + mitraillette + pno + meilleur buteur"},
    {player:"Lenny",amount:0,detail:"Rien"},
    {player:"Kevin",amount:0,detail:"Rien"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Simon",amount:7,detail:"Mitraillette + 2 contre-attaques"},
    {player:"Thomas",amount:3,detail:"Mitraillette"},
    {player:"Yanis",amount:0,detail:"Rien"},
    {player:"Benjamin",amount:3,detail:"Mitraillette"},
    {player:"Enzo",amount:0,detail:"Rien"},
  ]},
  { id:13, match:"vs Clermont", date:"Fév 2025", sortKey:13, entries:[
    {player:"Yanis",amount:5,detail:"Meilleure action + chaboula"},
    {player:"Adrien",amount:7,detail:"Sortie veille + penalty raté"},
    {player:"Paul",amount:6,detail:"Sortie veille + meilleur buteur"},
    {player:"Gabin",amount:6,detail:"Mitraillette + penalty raté + short"},
    {player:"Lenny",amount:0,detail:"Rien"},
    {player:"Kevin",amount:0,detail:"Rien"},
    {player:"Hugo",amount:5,detail:"Sortie veille"},
    {player:"Alexis",amount:5,detail:"Sortie veille"},
    {player:"Benjamin",amount:5,detail:"Sortie veille"},
    {player:"Enzo",amount:0,detail:"Rien"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Meyro",amount:0,detail:"Rien"},
  ]},
  { id:14, match:"vs Pérignat (2)", date:"Fév 2025", sortKey:14, entries:[
    {player:"Yanis",amount:6,detail:"2 relances + tir fantaisie"},
    {player:"Adrien",amount:0,detail:"Rien"},
    {player:"Paul",amount:6,detail:"Poule + meilleur buteur"},
    {player:"Gabin",amount:16,detail:"Mitraillette + penalty raté + vomi + 2 tirs fantaisie + meilleure action"},
    {player:"Lenny",amount:3,detail:"Pastis"},
    {player:"Kevin",amount:3,detail:"Mitraillette"},
    {player:"Hugo",amount:0,detail:"Rien"},
    {player:"Alexis",amount:3,detail:"Tir fantaisie + meilleure action"},
    {player:"Enzo",amount:0,detail:"Rien"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Thomas",amount:8,detail:"Chaboulat + mitraillette"},
    {player:"Simon",amount:0,detail:"Rien"},
  ]},
  { id:15, match:"vs Le Puy (2)", date:"Mars 2025", sortKey:15, entries:[
    {player:"Yanis",amount:2,detail:"Relance"},
    {player:"Adrien",amount:0,detail:"Rien"},
    {player:"Paul",amount:3,detail:"Meilleur buteur + meilleure action"},
    {player:"Gabin",amount:4,detail:"Penalty raté + meilleure action"},
    {player:"Kevin",amount:5,detail:"Chaboula"},
    {player:"Hugo",amount:2,detail:"2 tirs ratés en pivot"},
    {player:"Alexis",amount:0,detail:"Rien"},
    {player:"Enzo",amount:4,detail:"2 contre-attaques ratées"},
    {player:"Théo",amount:0,detail:"Rien"},
    {player:"Thomas",amount:0,detail:"Rien"},
    {player:"Simon",amount:0,detail:"Rien"},
  ]},
  { id:16, match:"vs St Germain (2)", date:"Mars 2025", sortKey:16, entries:[
    {player:"Yanis",amount:14,detail:"Ballon perché + 2 relances"},
    {player:"Adrien",amount:3,detail:"Mitraillette"},
    {player:"Paul",amount:15,detail:"Poule + sortie veille + pastis + penalty raté"},
    {player:"Gabin",amount:8,detail:"Chaboula + penalty raté + meilleure action"},
    {player:"Kevin",amount:5,detail:"Photo + gel douche + meilleure action"},
    {player:"Hugo",amount:1,detail:"Meilleure action"},
    {player:"Alexis",amount:5,detail:"Sortie veille"},
    {player:"Enzo",amount:13,detail:"Sortie veille + vomi + mitraillette"},
    {player:"Théo",amount:5,detail:"Contre-attaque + mitraillette"},
    {player:"Thomas",amount:0,detail:"Rien"},
    {player:"Meyro",amount:3,detail:"Mitraillette"},
    {player:"Lenny",amount:10,detail:"Sortie veille + vomi"},
  ]},
  { id:17, match:"vs Yssingeaux (3)", date:"Mars 2025", sortKey:17, entries:[
    {player:"Yanis",amount:5,detail:"Meilleure action + chaboula"},
    {player:"Fred",amount:5,detail:"Sortie veille"},
    {player:"Adrien",amount:5,detail:"Mitraillette + oubli matériel"},
    {player:"Paul",amount:3,detail:"Meilleure action + meilleur buteur"},
    {player:"Gabin",amount:5,detail:"Photo presse + retard 1 min + penalty"},
    {player:"Lenny",amount:0,detail:"Rien"},
    {player:"Kevin",amount:8,detail:"Chaboulat + mitraillette"},
    {player:"Hugo",amount:3,detail:"Gel douche x2"},
    {player:"Alexis",amount:0,detail:"Rien"},
    {player:"Enzo",amount:4,detail:"1 min retard + mitraillette"},
    {player:"Meyro",amount:3,detail:"Mitraillette"},
  ]},
];


export const EQ2 = [
  { id:101, match:"Éq2 vs Otaries de Langogne", date:"Sept 2024", sortKey:1, entries:[
    {player:"Bounty",amount:15,detail:"Bienvenue + 10 buts par un joueur + 2 relances ratées"},
    {player:"Erwan",amount:8,detail:"Bienvenue + défaite 10 buts + chaboulat"},
    {player:"Benjamin",amount:8,detail:"Bienvenue + défaite 10 buts + chaboulat"},
    {player:"Rémi",amount:13,detail:"Bienvenue + défaite 10 buts + meilleur buteur"},
    {player:"Coco",amount:8,detail:"Bienvenue + défaite 10 buts"},
    {player:"Killian",amount:8,detail:"Bienvenue + chaboula"},
    {player:"Clement",amount:3,detail:"Fantôme"},
    {player:"Arthur",amount:11,detail:"Bienvenue + mitraillette + défaite 10 buts"},
    {player:"Mathieu",amount:8,detail:"Bienvenue + défaite 10 buts"},
    {player:"Babeye",amount:10,detail:"Bienvenue + défaite 10 buts + pas de serviette"},
  ]},
  { id:102, match:"Éq2 vs Haut Velay Granitiques", date:"Oct 2024", sortKey:2, entries:[
    {player:"Bounty",amount:2,detail:"Relance ratée"},
    {player:"Erwan",amount:4,detail:"Penalty raté + meilleure action"},
    {player:"Romain G",amount:7,detail:"Bienvenue + oubli gel douche + mitraillette"},
    {player:"Rémi",amount:8,detail:"Sortie veille + penalty raté + meilleur buteur"},
    {player:"Coco",amount:4,detail:"Penalty raté + meilleure action"},
    {player:"Killian",amount:8,detail:"Bienvenue + chaboula"},
    {player:"Clement",amount:3,detail:"Fantôme"},
    {player:"Arthur",amount:4,detail:"Meilleure action + penalty raté"},
    {player:"Mathieu",amount:0,detail:"Rien"},
    {player:"Babeye",amount:5,detail:"Retard au match"},
  ]},
  { id:103, match:"Éq2 vs Yssingeaux", date:"Oct 2024", sortKey:3, entries:[
    {player:"Bounty",amount:6,detail:"Défaite + 14 buts"},
    {player:"Erwan",amount:3,detail:"Défaite"},
    {player:"Killian",amount:3,detail:"Défaite"},
    {player:"Rémi",amount:15,detail:"Défaite + oubli caleçon + sortie veille + oubli photo + mitraillette"},
    {player:"Coco",amount:10,detail:"Défaite + sortie veille"},
    {player:"Benjamin",amount:8,detail:"Défaite + sortie veille"},
    {player:"Arthur",amount:11,detail:"Défaite + meilleur buteur + tir fantaisie + chaboulat"},
    {player:"Clement",amount:3,detail:"Défaite"},
    {player:"David",amount:3,detail:"Défaite"},
    {player:"Paul",amount:2,detail:"Meilleure action"},
  ]},
  { id:104, match:"Éq2 vs St Flour", date:"Nov 2024", sortKey:4, entries:[
    {player:"Babeye",amount:3,detail:"Mitraillette"},
    {player:"Erwan",amount:5,detail:"Oubli serviette + mitraillette"},
    {player:"Killian",amount:9,detail:"Absent entraînement + mitraillette + maillot envers"},
    {player:"Rémi",amount:0,detail:"Rien"},
    {player:"Coco",amount:2,detail:"Penalty raté"},
    {player:"Mathieu",amount:3,detail:"Mitraillette"},
    {player:"Romain G",amount:3,detail:"Mitraillette"},
    {player:"Arthur",amount:3,detail:"Meilleur buteur + tir fantaisie"},
    {player:"Kevin",amount:10,detail:"Chaboula + 0/6 20 min + mitraillette + meilleure action"},
    {player:"David",amount:2,detail:"Meilleure action"},
  ]},
  { id:105, match:"Éq2 Coupe vs Yssingeaux", date:"Nov 2024", sortKey:5, entries:[
    {player:"Babeye",amount:3,detail:"Mitraillette"},
    {player:"Erwan",amount:3,detail:"Penalty raté + meilleur buteur"},
    {player:"Killian",amount:5,detail:"Pas de matériel + pas gel douche + maillot envers"},
    {player:"Rémi",amount:0,detail:"Rien"},
    {player:"Coco",amount:2,detail:"Penalty raté"},
    {player:"Mathieu",amount:0,detail:"Rien"},
    {player:"David",amount:0,detail:"Rien"},
    {player:"Clement",amount:0,detail:"Rien"},
    {player:"Arthur",amount:0,detail:"Rien"},
    {player:"Yanis",amount:9,detail:"Chaboula + mitraillette + tir fantaisie pris"},
  ]},
  { id:106, match:"Éq2 vs Le Monastier", date:"Déc 2024", sortKey:6, entries:[
    {player:"Babeye",amount:7,detail:"Mitraillette + défaite"},
    {player:"Erwan",amount:6,detail:"Penalty raté + défaite"},
    {player:"Killian",amount:12,detail:"Sortie veille + pas matériel + défaite"},
    {player:"Rémi",amount:9,detail:"Sortie veille + défaite"},
    {player:"Coco",amount:5,detail:"Meilleur buteur + défaite"},
    {player:"Pierre Edouard",amount:12,detail:"Bienvenue + 10 buts même joueur + défaite"},
    {player:"Romain G",amount:7,detail:"Mitraillette + sortie veille + défaite"},
    {player:"Arthur",amount:12,detail:"Mitraillette + sortie veille + défaite"},
    {player:"David",amount:9,detail:"Chaboula + défaite"},
    {player:"Alexis",amount:7,detail:"Mitraillette + défaite"},
  ]},
  { id:107, match:"Éq2 vs Landos", date:"Jan 2025", sortKey:7, entries:[
    {player:"Erwan",amount:5,detail:"Mitraillette + penalty manqué"},
    {player:"Killian",amount:3,detail:"Mitraillette"},
    {player:"Rémi",amount:0,detail:"Rien"},
    {player:"Coco",amount:5,detail:"Penalty manqué + mitraillette + 10 buts par le 9 + chaboula"},
    {player:"Pierre Edouard",amount:2,detail:"10 buts par le même gars"},
    {player:"Benjamin",amount:2,detail:"Penalty manqué"},
    {player:"David",amount:0,detail:"Rien"},
    {player:"Fred",amount:4,detail:"12 buts par le 9 + relance loupée"},
    {player:"Mathieu",amount:5,detail:"Sortie veille"},
    {player:"Simon",amount:0,detail:"Rien"},
  ]},
  { id:108, match:"Éq2 vs Est 43", date:"Jan 2025", sortKey:8, entries:[
    {player:"Babeye",amount:6,detail:"Caleçon envers + défaite dom. écart 5-9"},
    {player:"Killian",amount:9,detail:"Oubli matériel + mitraillette + défaite dom. écart 5-9"},
    {player:"Rémi",amount:9,detail:"Chaboula + défaite dom. écart 5-9"},
    {player:"Coco",amount:9,detail:"Penalty raté + mitraillette + défaite dom. écart 5-9"},
    {player:"Pierre Edouard",amount:8,detail:"Meilleure action + relance ratée + défaite dom. écart 5-9"},
    {player:"David",amount:4,detail:"Défaite dom. écart 5-9"},
    {player:"Arthur",amount:4,detail:"Défaite dom. écart 5-9"},
    {player:"Mathieu",amount:9,detail:"Penalty raté + mitraillette + défaite dom. écart 5-9"},
    {player:"Clement",amount:5,detail:"1 arrêt + défaite dom. écart 5-9"},
  ]},
  { id:109, match:"Éq2 vs Langogne", date:"Jan 2025", sortKey:9, entries:[
    {player:"Babeye",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Killian",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Erwan",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Rémi",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Coco",amount:12,detail:"Penalty raté + défaite dom. écart 10 + chaboula"},
    {player:"Pierre Edouard",amount:7,detail:"Meilleure action + non port chaboula + défaite dom. écart 10"},
    {player:"David",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Clement",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Arthur",amount:9,detail:"Mitraillette + penalty raté + défaite dom. écart 10"},
    {player:"Mathieu",amount:5,detail:"Défaite dom. écart 10"},
    {player:"Meyro",amount:7,detail:"Mitraillette + défaite dom. écart 10"},
    {player:"Bounty",amount:5,detail:"Défaite dom. écart 10"},
  ]},
  { id:110, match:"Éq2 vs Nord Lozère", date:"Fév 2025", sortKey:10, entries:[
    {player:"Babeye",amount:1,detail:"Rien de notable"},
    {player:"Erwan",amount:2,detail:"Penalty raté"},
    {player:"Killian",amount:6,detail:"Sortie veille + maillot envers"},
    {player:"Rémi",amount:5,detail:"Sortie veille"},
    {player:"Coco",amount:14,detail:"Sortie veille + penalty raté + mitraillette + chaboula"},
    {player:"Pierre Edouard",amount:1,detail:"Retard"},
    {player:"David",amount:2,detail:"Mitraillette"},
    {player:"Arthur",amount:2,detail:"Mitraillette"},
    {player:"Clement",amount:2,detail:"Mitraillette"},
    {player:"Mathieu",amount:2,detail:"Meilleur buteur"},
    {player:"Benjamin",amount:1,detail:"Rien de notable"},
    {player:"Alexis",amount:2,detail:"Mitraillette"},
  ]},
  { id:111, match:"Éq2 vs St Flour (Coupe)", date:"Fév 2025", sortKey:11, entries:[
    {player:"Babeye",amount:4,detail:"Mitraillette + pas savon"},
    {player:"Killian",amount:4,detail:"Mitraillette"},
    {player:"Rémi",amount:4,detail:"Meilleur buteur + chaboula + relance ratée"},
    {player:"Coco",amount:4,detail:"Penalty manqué + mitraillette"},
    {player:"Pierre Edouard",amount:7,detail:"Meilleur buteur + chaboula + relance ratée"},
    {player:"Arthur",amount:2,detail:"Mitraillette"},
    {player:"Clement",amount:2,detail:"Mitraillette"},
    {player:"Mathieu",amount:4,detail:"Penalty raté + puy de pétrole"},
    {player:"Kevin",amount:2,detail:"Mitraillette"},
    {player:"Meyro",amount:0,detail:"Rien"},
    {player:"Alexis",amount:4,detail:"Mitraillette + contre-attaque ratée"},
  ]},
  { id:112, match:"Éq2 vs Yssingeaux (Coupe)", date:"Fév 2025", sortKey:12, entries:[
    {player:"Babeye",amount:2,detail:"Mitraillette"},
    {player:"Killian",amount:10,detail:"Mitraillette + tir fantaisie + oubli photo + pas savon + pas serviette"},
    {player:"Rémi",amount:4,detail:"Relance ratée + mitraillette"},
    {player:"Coco",amount:13,detail:"Penalty manqué + oubli matériel + mitraillette + meilleure action"},
    {player:"Pierre Edouard",amount:4,detail:"Tir fantaisie pris + relance ratée + mitraillette"},
    {player:"Arthur",amount:2,detail:"Mitraillette"},
    {player:"Clement",amount:0,detail:"Rien"},
    {player:"Mathieu",amount:4,detail:"Penalty raté + puy de pétrole"},
    {player:"Kevin",amount:2,detail:"Mitraillette"},
    {player:"Meyro",amount:0,detail:"Rien"},
    {player:"Alexis",amount:4,detail:"Mitraillette + contre-attaque ratée"},
    {player:"David",amount:2,detail:"Tir fantaisie"},
  ]},
  { id:113, match:"Éq2 vs Sauguains de Saugues", date:"Mars 2025", sortKey:13, entries:[
    {player:"Babeye",amount:0,detail:"Rien"},
    {player:"Killian",amount:20,detail:"Mitraillette + vomi + oubli photo + pas savon + sortie veille + meilleure action"},
    {player:"Rémi",amount:0,detail:"Rien"},
    {player:"Coco",amount:9,detail:"Retard + penalty manqué + sortie veille"},
    {player:"Pierre Edouard",amount:9,detail:"12 buts par le 9 + défaite"},
    {player:"Benjamin",amount:2,detail:"Penalty manqué"},
    {player:"David",amount:0,detail:"Rien"},
    {player:"Fred",amount:4,detail:"12 buts par le 9 + relance loupée"},
    {player:"Mathieu",amount:5,detail:"Sortie veille"},
    {player:"Simon",amount:5,detail:"Sortie veille"},
  ]},
  { id:114, match:"Éq2 vs Haut Velay Granitique (2)", date:"Mars 2025", sortKey:14, entries:[
    {player:"Babeye",amount:4,detail:"Mitraillette + défaite"},
    {player:"Killian",amount:12,detail:"Chaboula + défaite + sortie veille"},
    {player:"Rémi",amount:2,detail:"Défaite"},
    {player:"Coco",amount:7,detail:"Meilleur buteur + défaite"},
    {player:"Pierre Edouard",amount:22,detail:"Meilleur buteur + 14 buts par le 11 + défaite + pire perf réalisable"},
    {player:"Romain G",amount:7,detail:"Mitraillette + sortie veille + défaite"},
    {player:"Arthur",amount:12,detail:"Mitraillette + sortie veille + défaite"},
    {player:"David",amount:9,detail:"Chaboula + défaite"},
    {player:"Clement",amount:2,detail:"Défaite"},
    {player:"Mathieu",amount:2,detail:"Défaite"},
    {player:"Alexis",amount:7,detail:"Mitraillette + défaite"},
  ]},
];


export const HISTORICAL_MATCHES = [...EQ1, ...EQ2];
