export const INITIAL_RULES = [
  { id: 1, name: "Bienvenue dans la caisse noire", amount: 3 },
  { id: 2, name: "Mitraillette", amount: 3 },
  { id: 3, name: "Relance ratée", amount: 2 },
  { id: 4, name: "Contre-attaque ratée", amount: 2 },
  { id: 5, name: "Tir fantaisie raté", amount: 2 },
  { id: 6, name: "Tir fantaisie pris (adverse)", amount: 1 },
  { id: 7, name: "Penalty raté", amount: 2 },
  { id: 8, name: "Chaboulat / Chaboula", amount: 5 },
  { id: 9, name: "Non port du chaboulat (photo)", amount: 2 },
  { id: 10, name: "Sortie veille de match", amount: 5 },
  { id: 11, name: "Retard entraînement (par min)", amount: 1 },
  { id: 12, name: "Fantôme", amount: 3 },
  { id: 13, name: "Poule non officielle", amount: 5 },
  { id: 14, name: "Serviette oubliée", amount: 2 },
  { id: 15, name: "Gel douche oublié", amount: 1 },
  { id: 16, name: "Short oublié", amount: 1 },
  { id: 17, name: "Caleçon oublié", amount: 1 },
  { id: 18, name: "Chasuble oubliée", amount: 1 },
  { id: 19, name: "Maillot à l'envers", amount: 1 },
  { id: 20, name: "Gourde entraînement oubliée", amount: 1 },
  { id: 21, name: "Puit de pétrole", amount: 3 },
  { id: 22, name: "2 min pour contestation", amount: 2 },
  { id: 23, name: "Carton rouge", amount: 20 },
  { id: 24, name: "Vomi en soirée", amount: 5 },
  { id: 25, name: "Pastis", amount: 3 },
  { id: 26, name: "Ballon perché", amount: 10 },
  { id: 27, name: "Usage téléphone sur le banc", amount: 5 },
  { id: 28, name: "Non respect du Movember", amount: 5 },
  { id: 29, name: "Movember (cotisation)", amount: 1 },
  { id: 30, name: "Défaite écart 5-9 buts dom.", amount: 4 },
  { id: 31, name: "Défaite écart 10+ buts dom.", amount: 5 },
  { id: 32, name: "Défaite 7-9 buts écart ext.", amount: 3 },
  { id: 33, name: "Défaite 10+ buts écart ext.", amount: 5 },
  { id: 34, name: "10 buts pris par le même joueur", amount: 3 },
  { id: 35, name: "Meilleure action du match", amount: 2 },
  { id: 36, name: "Meilleur buteur", amount: 1 },
  { id: 37, name: "Photo presse", amount: 2 },
  { id: 38, name: "Savon oublié", amount: 1 },
  { id: 39, name: "Pire performance réalisable", amount: 5 },
];

export const PAYMENT_TOTALS = {
  "Hugo": 33, "Adrien": 72, "Yanis": 147.5, "Fred": 83,
  "Paul": 189, "Meyro": 33, "David": 52, "Enzo": 24,
  "Lenny": 76, "Kevin": 70.5, "Gabin": 115.5, "Thomas": 66.5,
  "Killian": 111.5, "Alexis": 76, "Simon": 50.5, "Rémi": 82,
  "Théo": 92.5, "Benjamin": 37.5, "Mathieu": 62.5, "Coco": 104.5,
  "Arthur": 86, "Babeye": 62.5, "Clement": 39.5, "Bounty": 30.5,
  "Erwan": 35, "Romain G": 17, "Pierre Edouard": 48,
};

export const INITIAL_PAYMENTS = [
  {player:"Adrien",total:72,paid:40},
  {player:"Alexis",total:76,paid:0},
  {player:"Arthur",total:86,paid:0},
  {player:"Babeye",total:62.5,paid:0},
  {player:"Benjamin",total:37.5,paid:0},
  {player:"Bounty",total:30.5,paid:0},
  {player:"Clement",total:39.5,paid:0},
  {player:"Coco",total:104.5,paid:24},
  {player:"David",total:52,paid:0},
  {player:"Enzo",total:24,paid:0},
  {player:"Erwan",total:35,paid:0},
  {player:"Fred",total:83,paid:0},
  {player:"Gabin",total:115.5,paid:0},
  {player:"Hugo",total:33,paid:20},
  {player:"Kevin",total:70.5,paid:25},
  {player:"Killian",total:111.5,paid:0},
  {player:"Lenny",total:76,paid:0},
  {player:"Mathieu",total:62.5,paid:0},
  {player:"Meyro",total:33,paid:0},
  {player:"Paul",total:189,paid:62},
  {player:"Pierre Edouard",total:48,paid:0},
  {player:"Romain G",total:17,paid:0},
  {player:"Rémi",total:82,paid:42},
  {player:"Simon",total:50.5,paid:0},
  {player:"Thomas",total:66.5,paid:0},
  {player:"Théo",total:92.5,paid:59},
  {player:"Yanis",total:147.5,paid:72},
];

export const INITIAL_CALENDAR = [
  {id:1,date:"Sept 2024",sortKey:1,opponent:"Clermont Métropole",home:false,location:"Clermont-Fd",team:"Éq1"},
  {id:101,date:"Sept 2024",sortKey:1,opponent:"Otaries de Langogne",home:false,location:"Langogne",team:"Éq2"},
  {id:2,date:"Oct 2024",sortKey:2,opponent:"Pérignat",home:true,location:"Langeac",team:"Éq1"},
  {id:102,date:"Oct 2024",sortKey:2,opponent:"Haut Velay Granitiques",home:false,location:"Craponne",team:"Éq2"},
  {id:3,date:"Oct 2024",sortKey:3,opponent:"Le Puy",home:false,location:"Le Puy",team:"Éq1"},
  {id:103,date:"Oct 2024",sortKey:3,opponent:"Yssingeaux",home:false,location:"Yssingeaux",team:"Éq2"},
  {id:4,date:"Oct 2024",sortKey:4,opponent:"Yssingeaux",home:true,location:"Langeac",team:"Éq1"},
  {id:5,date:"Nov 2024",sortKey:5,opponent:"St Germain",home:false,location:"St Germain",team:"Éq1"},
  {id:104,date:"Nov 2024",sortKey:5,opponent:"St Flour",home:false,location:"St Flour",team:"Éq2"},
  {id:6,date:"Nov 2024",sortKey:6,opponent:"St Flour (Coupe de France)",home:true,location:"Langeac",team:"Éq1"},
  {id:105,date:"Nov 2024",sortKey:6,opponent:"Yssingeaux (Coupe)",home:false,location:"Yssingeaux",team:"Éq2"},
  {id:7,date:"Nov 2024",sortKey:7,opponent:"Romagnat",home:false,location:"Romagnat",team:"Éq1"},
  {id:8,date:"Déc 2024",sortKey:8,opponent:"Yssingeaux (2)",home:true,location:"Langeac",team:"Éq1"},
  {id:106,date:"Déc 2024",sortKey:8,opponent:"Le Monastier",home:false,location:"Le Monastier",team:"Éq2"},
  {id:9,date:"Déc 2024",sortKey:9,opponent:"Est 43",home:true,location:"Langeac",team:"Éq1"},
  {id:10,date:"Déc 2024",sortKey:10,opponent:"Chamalière",home:false,location:"Chamalière",team:"Éq1"},
  {id:107,date:"Jan 2025",sortKey:11,opponent:"Landos",home:false,location:"Landos",team:"Éq2"},
  {id:11,date:"Jan 2025",sortKey:11,opponent:"Aurillac",home:true,location:"Langeac",team:"Éq1"},
  {id:108,date:"Jan 2025",sortKey:12,opponent:"Est 43",home:true,location:"Langeac",team:"Éq2"},
  {id:12,date:"Jan 2025",sortKey:12,opponent:"Vichy",home:false,location:"Vichy",team:"Éq1"},
  {id:109,date:"Jan 2025",sortKey:13,opponent:"Langogne",home:true,location:"Langeac",team:"Éq2"},
  {id:13,date:"Fév 2025",sortKey:13,opponent:"Clermont",home:true,location:"Langeac",team:"Éq1"},
  {id:110,date:"Fév 2025",sortKey:14,opponent:"Nord Lozère",home:false,location:"Nord Lozère",team:"Éq2"},
  {id:111,date:"Fév 2025",sortKey:14,opponent:"St Flour (Coupe)",home:false,location:"St Flour",team:"Éq2"},
  {id:14,date:"Fév 2025",sortKey:14,opponent:"Pérignat (2)",home:false,location:"Pérignat",team:"Éq1"},
  {id:112,date:"Fév 2025",sortKey:15,opponent:"Yssingeaux (Coupe)",home:false,location:"Yssingeaux",team:"Éq2"},
  {id:15,date:"Mars 2025",sortKey:15,opponent:"Le Puy (2)",home:true,location:"Langeac",team:"Éq1"},
  {id:113,date:"Mars 2025",sortKey:16,opponent:"Sauguains de Saugues",home:false,location:"Saugues",team:"Éq2"},
  {id:16,date:"Mars 2025",sortKey:16,opponent:"St Germain (2)",home:false,location:"St Germain",team:"Éq1"},
  {id:114,date:"Mars 2025",sortKey:17,opponent:"Haut Velay Granitique (2)",home:false,location:"Craponne",team:"Éq2"},
  {id:17,date:"Mars 2025",sortKey:17,opponent:"Yssingeaux (3)",home:true,location:"Langeac",team:"Éq1"},
];
