export const INITIAL_RULES = [
  { id: 1, name: "Bienvenue dans la caisse noire", amount: 3 },
  { id: 2, name: "Mitraillette", amount: 3 },
  { id: 3, name: "Relance ratée", amount: 2 },
  { id: 4, name: "Contre-attaque ratée", amount: 2 },
  { id: 5, name: "Tir fantaisie raté", amount: 2 },
  { id: 6, name: "Tir fantaisie pris (adverse)", amount: 1 },
  { id: 7, name: "Penalty raté", amount: 2 },
  { id: 8, name: "Chaboulat / Chaboula", amount: 5 },
  { id: 9, name: "Non port du chaboulat (photo)", amount: 2 },
  { id: 10, name: "Sortie veille de match", amount: 5 },
  { id: 11, name: "Retard entraînement (par min)", amount: 1 },
  { id: 12, name: "Fantôme", amount: 3 },
  { id: 13, name: "Poule non officielle", amount: 5 },
  { id: 14, name: "Serviette oubliée", amount: 2 },
  { id: 15, name: "Gel douche oublié", amount: 1 },
  { id: 16, name: "Short oublié", amount: 1 },
  { id: 17, name: "Caleçon oublié", amount: 1 },
  { id: 18, name: "Chasuble oubliée", amount: 1 },
  { id: 19, name: "Maillot à l'envers", amount: 1 },
  { id: 20, name: "Gourde entraînement oubliée", amount: 1 },
  { id: 21, name: "Puit de pétrole", amount: 3 },
  { id: 22, name: "2 min pour contestation", amount: 2 },
  { id: 23, name: "Carton rouge", amount: 20 },
  { id: 24, name: "Vomi en soirée", amount: 5 },
  { id: 25, name: "Pastis", amount: 3 },
  { id: 26, name: "Ballon perché", amount: 10 },
  { id: 27, name: "Usage téléphone sur le banc", amount: 5 },
  { id: 28, name: "Non respect du Movember", amount: 5 },
  { id: 29, name: "Movember (cotisation)", amount: 1 },
  { id: 30, name: "Défaite écart 5-9 buts dom.", amount: 4 },
  { id: 31, name: "Défaite écart 10+ buts dom.", amount: 5 },
  { id: 32, name: "Défaite 7-9 buts écart ext.", amount: 3 },
  { id: 33, name: "Défaite 10+ buts écart ext.", amount: 5 },
  { id: 34, name: "10 buts pris par le même joueur", amount: 3 },
  { id: 35, name: "Meilleure action du match", amount: 2 },
  { id: 36, name: "Meilleur buteur", amount: 1 },
  { id: 37, name: "Photo presse", amount: 2 },
  { id: 38, name: "Savon oublié", amount: 1 },
  { id: 39, name: "Pire performance réalisable", amount: 5 },
];

// Nouvelle saison : paiements vidés (repartent de zéro)
export const INITIAL_PAYMENTS = [];

// Nouvelle saison : calendrier 2025-2026 (Seniors Masculins - Excellence - Poule 1)
export const INITIAL_CALENDAR = [
  {id:1,date:"12/09/2026",sortKey:1,opponent:"Limas HB",home:false,location:"Limas",team:"Éq1"},
  {id:2,date:"19/09/2026",sortKey:2,opponent:"St Flour HB",home:true,location:"Langeac",team:"Éq1"},
  {id:3,date:"03/10/2026",sortKey:3,opponent:"US Issoire HB",home:true,location:"Langeac",team:"Éq1"},
  {id:4,date:"10/10/2026",sortKey:4,opponent:"Echalas HBC",home:false,location:"Echalas",team:"Éq1"},
  {id:5,date:"24/10/2026",sortKey:5,opponent:"AS Romagnat HB",home:true,location:"Langeac",team:"Éq1"},
  {id:6,date:"14/11/2026",sortKey:6,opponent:"AL Aubière HB",home:false,location:"Aubière",team:"Éq1"},
  {id:7,date:"28/11/2026",sortKey:7,opponent:"Firminy Vallée de l'ondaine HB",home:true,location:"Langeac",team:"Éq1"},
  {id:8,date:"05/12/2026",sortKey:8,opponent:"Roanne Riorges HB",home:false,location:"Roanne",team:"Éq1"},
  {id:9,date:"12/12/2026",sortKey:9,opponent:"HBC Lyon",home:true,location:"Langeac",team:"Éq1"},
  {id:10,date:"09/01/2027",sortKey:10,opponent:"Saint-Etienne Handball",home:false,location:"Saint-Etienne",team:"Éq1"},
  {id:11,date:"16/01/2027",sortKey:11,opponent:"Amplepuis HBC",home:true,location:"Langeac",team:"Éq1"},
  {id:12,date:"23/01/2027",sortKey:12,opponent:"Limas HB",home:true,location:"Langeac",team:"Éq1"},
  {id:13,date:"30/01/2027",sortKey:13,opponent:"St Flour HB",home:false,location:"St Flour",team:"Éq1"},
  {id:14,date:"06/02/2027",sortKey:14,opponent:"US Issoire HB",home:false,location:"Issoire",team:"Éq1"},
  {id:15,date:"06/03/2027",sortKey:15,opponent:"Echalas HBC",home:true,location:"Langeac",team:"Éq1"},
  {id:16,date:"13/03/2027",sortKey:16,opponent:"AS Romagnat HB",home:false,location:"Romagnat",team:"Éq1"},
  {id:17,date:"20/03/2027",sortKey:17,opponent:"AL Aubière HB",home:true,location:"Langeac",team:"Éq1"},
  {id:18,date:"03/04/2027",sortKey:18,opponent:"Firminy Vallée de l'ondaine HB",home:false,location:"Firminy",team:"Éq1"},
  {id:19,date:"10/04/2027",sortKey:19,opponent:"Roanne Riorges HB",home:true,location:"Langeac",team:"Éq1"},
  {id:20,date:"01/05/2027",sortKey:20,opponent:"HBC Lyon",home:false,location:"Lyon",team:"Éq1"},
  {id:21,date:"22/05/2027",sortKey:21,opponent:"Saint-Etienne Handball",home:true,location:"Langeac",team:"Éq1"},
  {id:22,date:"29/05/2027",sortKey:22,opponent:"Amplepuis HBC",home:false,location:"Amplepuis",team:"Éq1"},
];
